name: cached_network_image_plus
description: "Effortlessly cache network images, create rounded corners, and apply customizable shadows for a refined look and feel."
version: 0.0.3
homepage: https://github.com/OfficialKunalGandhi/flutter_cached_network_image_plus
topics:
  - cache
  - image
  - network-image

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

